version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      typescript:
        dependency-type: development
        patterns:
          - typescript
        update-types:
          - minor
          - patch

      production-dependencies:
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - minor
          - patch

      development-dependencies:
        dependency-type: development
        patterns:
          - '*'
        exclude-patterns:
          - typescript
        update-types:
          - major
          - minor
          - patch

    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      actions-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
